package com.dev_talk

const val LIST_PROFESSIONS_KEY = "LIST_PROFESSIONS_KEY"
const val LIST_SELECTED_PROFESSIONS_KEY = "LIST_SELECTED_PROFESSIONS_KEY"
const val LIST_TAGS_KEY = "LIST_TAGS_KEY"
const val LIST_SELECTED_TAGS_KEY = "LIST_SELECTED_TAGS_KEY"
